[package]
name = "ape"
version = "0.1.0"
authors = ["Isaac van Bakel <ivb@vanbakel.io>"]
edition = "2018"

[lib]
name = "ape"
path = 'src/lib.rs'
proc-macro = true

[dependencies]
backtracking_iterator = "0.1.0"

